import { Palette, Button, ComboBox, GroupBox, GridBox, Slider, HorizontalBox, VerticalBox, ProgressIndicator } from "std-widgets.slint";
export component AppWindow inherits Window {
    in property <image> texture <=> i.source;
    out property <length> requested-texture-width: i.width;
    out property <length> requested-texture-height: i.height;
    title: @tr("Slint & Vello");
    icon: @image-url("../assets/window-icon.png");
    preferred-width: 500px;
    preferred-height: 600px;
    background: black;
    Rectangle {
        i := Image {
            image-fit: fill;
            width: 100%;
            height: 100%;
            Text {
                text: "Slint & Vello";
                font-family: "Fira Code";
                font-size: 24px;
                font-weight: 500;
                color: white;
            }
        }
    }
}
